---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: default
 name: role-pods-and-services
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/logs", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-pods-and-services
 namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default
roleRef:
 kind: Role
 name: role-pods-and-services
 apiGroup: rbac.authorization.k8s.io
