apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  labels:
    jenkins/kube-default: "true"
    app: jenkins
    component: agent
spec:
  containers:
    - name: 'rust'
      image: 'rust:1.31.1-slim'
      command:
      - cat
      tty: true
    - name: dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}